# Generated by Django 6.0.5 on 2026-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='suspicious_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
